//
// ApplicationRole.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct ApplicationRole: Serializable {

    public var _description: String?
    public var _id: String?
    public var name: String?
    public var normalizedName: String?
    public var concurrencyStamp: String?

    public init(_description: String?, _id: String?, name: String?, normalizedName: String?, concurrencyStamp: String?) {
        self._description = _description
        self._id = _id
        self.name = name
        self.normalizedName = normalizedName
        self.concurrencyStamp = concurrencyStamp
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case _id = "id"
        case name
        case normalizedName
        case concurrencyStamp
    }


}

