//
// LoginResponse.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct LoginResponse: Serializable {

    //
        //TODO:
    
    //
    public var token: String?
    public var claims: [Claim]?

    public init(token: String?, claims: [Claim]?) {
        self.token = token
        self.claims = claims
    }


}

public struct ServiceResponse : Serializable{
    public var isSuccessful: Bool
    public var error : String
    //public var result : T
    
    public init(isSuccessful: Bool, error: String) {
           self.isSuccessful = isSuccessful
           self.error = error
    }
    
}

