//
// MenuResponse.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct MenuResponse: Serializable {

    public var url: String?
    public var name: String?
    public var children: [MenuResponse]?

    public init(url: String?, name: String?, children: [MenuResponse]?) {
        self.url = url
        self.name = name
        self.children = children
    }


}

