//
// ResetPasswordRequest.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct ResetPasswordRequest: Serializable {

    public var token: String?
    public var email: String?
    public var password: String?
    public var confirmPassword: String?

    public init(token: String?, email: String?, password: String?, confirmPassword: String?) {
        self.token = token
        self.email = email
        self.password = password
        self.confirmPassword = confirmPassword
    }


}

