//
// RoleUserResponse.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct RoleUserResponse: Serializable {

    public var username: String?
    public var email: String?

    public init(username: String?, email: String?) {
        self.username = username
        self.email = email
    }


}

