//
// ApplicationUser.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct ApplicationUser: Serializable {

    public var _id: String?
    public var userName: String?
    public var normalizedUserName: String?
    public var email: String?
    public var normalizedEmail: String?
    public var emailConfirmed: Bool?
    public var passwordHash: String?
    public var securityStamp: String?
    public var concurrencyStamp: String?
    public var phoneNumber: String?
    public var phoneNumberConfirmed: Bool?
    public var twoFactorEnabled: Bool?
    public var lockoutEnd: Date?
    public var lockoutEnabled: Bool?
    public var accessFailedCount: Int?

    public init(_id: String?, userName: String?, normalizedUserName: String?, email: String?, normalizedEmail: String?, emailConfirmed: Bool?, passwordHash: String?, securityStamp: String?, concurrencyStamp: String?, phoneNumber: String?, phoneNumberConfirmed: Bool?, twoFactorEnabled: Bool?, lockoutEnd: Date?, lockoutEnabled: Bool?, accessFailedCount: Int?) {
        self._id = _id
        self.userName = userName
        self.normalizedUserName = normalizedUserName
        self.email = email
        self.normalizedEmail = normalizedEmail
        self.emailConfirmed = emailConfirmed
        self.passwordHash = passwordHash
        self.securityStamp = securityStamp
        self.concurrencyStamp = concurrencyStamp
        self.phoneNumber = phoneNumber
        self.phoneNumberConfirmed = phoneNumberConfirmed
        self.twoFactorEnabled = twoFactorEnabled
        self.lockoutEnd = lockoutEnd
        self.lockoutEnabled = lockoutEnabled
        self.accessFailedCount = accessFailedCount
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userName
        case normalizedUserName
        case email
        case normalizedEmail
        case emailConfirmed
        case passwordHash
        case securityStamp
        case concurrencyStamp
        case phoneNumber
        case phoneNumberConfirmed
        case twoFactorEnabled
        case lockoutEnd
        case lockoutEnabled
        case accessFailedCount
    }


}

