//
// ForgotPasswordRequest.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct ForgotPasswordRequest: Serializable {

    public var email: String

    public init(email: String) {
        self.email = email
    }


}

