//
// RoleClaimPostRequest.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct RoleClaimPostRequest: Serializable {

    public var name: String

    public init(name: String) {
        self.name = name
    }


}

