//
// UserPatchRequest.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct UserPatchRequest: Serializable {

    public var email: String
    public var phoneNumber: String?

    public init(email: String, phoneNumber: String?) {
        self.email = email
        self.phoneNumber = phoneNumber
    }


}

